### PR TITLE
N Gaussian Fit Included

### PR DESCRIPTION
**Pull request by jczamorac**
Hi, 
interesting project! I made a small modification that is helpful for our analysis.
I just included a function to fit N Gaussian peaks. The variable N (npeaks) is defined as a global const. There should be a smarter way to define this variable.
Cheers,
Juan

### CODE REVIEW

**Comment by xination** [comment]
Hi Juan, thank you for your contributions. 
I will review the codes in couple of days.
Before reading the details, just wondering what your design for the default values for the fitting is.

**Comment by jczamorac** [comment]
Great, thanks!
it is for a basic analysis of a nuclear reaction experiment. Yes, I included several default values that are OK for tests I made, but of course we can set them in a more general way.

**Comment by xination** [comment]
Hi Juan,
Sorry for the late reply. I finally get some time to read the code update from the 8/12 version. 
You extension to triple Gaussian is Good, 
but I wish it could be more flexible, for example, sigma can be set by user, etc...
or be capable to do 4 or 5 Gaussian fits.

It is better to use a dialogue for users to input the sigma values.
I will work on this in a couple of few days, and then send you the patch file.

Thank you for your contributions.
Pei-Luan Tai

**Comment by jczamorac** [comment]
Hi Pei-Luan,

no worries, I understand. 
Your code has been of great help, so it is a pleasure contributing on it!

The gaussian fit function can be extended to any value, we just need to set a npeaks variable to any value. 
I fixed the sigmas just because I needed to make a quick analysis, but in principle it can be given by the users via a dialogue window. I think it would be easier for the user to give a FWHM guess of the peak with markers and plot a horizontal line to each peak. What do you think?

Thanks,
Juan

**Comment by xination** [comment]
Hi Juan,

I have extended your original idea of N Gaussian fit as the following:
* user can choose to do 2, 3, ... up to 10 Gaussian function fits.
  step1: press d ( pop up the operation windows for 1d histogram)
  step2:  type in **set fitN 4**
  for 4 Gaussian fit.
  ( current default, fitN=2)

  to use it 
  step1: choose the fitting range (xmin, xmax) by just mouse click.
  step2: choose the peaks by ctrl+mouse click. 
  step3: press T ( now it is still kkey_T, but I think I will merge it into kkey_G)
   there will be a windows for the initial height, center, sigma values, you can fine tune them.
   after pressing OK button, it will show the results on message box on the top.

* the # of aux lines ( general pick N) is modified according to the fitN 
   e.g. if we fit 3 Gaussian, there are only 3 aux lines.
   

* Here is a figure for demonstrating the results for 4 Gaussian fit with bg.
[ https://imgur.com/0Gw8EvI ](url)
---------------------------------------------------
I don't know what will be the best way to do merging.
You have another 3 commits after the very first one on Aug 12,
and I worked on the base of Aug 12 version.
If I merge, it may mess up due to  possible conflict. 

I have created a new branch "exp_br", which contains your and my major update.
Would you like to take a look? 


Thank you again.
Best Regards,
Pei-Luan Tai

---------------------------------------------------
something I remove:
* Set_Linear_Background ( kkey_l), it is because there is already one (kkey_1)

* Reset_Functions, it is because I think users can just set another background values,
and param[] for the fitting is updated every time, and so there is no need to do it.

**Comment by jczamorac** [comment]
Hi Pei-Luan Tai,

Sorry for the late replay.

I liked very much the changes you made to the code. The user can  decide how many peak want to fit through a dialogue window and the initial guess for sigma is very reasonable.

I have a couple of commits more which are small changes in the integration function and functionalities kkey_l and kkey_0. I am goint ot create a new branch "develop", so we can discuss some changes and merge them one by one.

BTW, I forgot to tell you the real aim of the functions kkey_l and kkey_0. 
kkey_l is different then kkey_1 because in the first case the user can give a linear bg estimation by giving two points. This is useful when you want to have line (by eye) that connects the  left and right sides of a peak. If instead we use kkey_1, the fitting will modify the line due to the points of the peak.
kkey_0 is used more like a reset (sometimes it is important to have one). It cleans all markers and functions, in particular the bg parameters. Remember that param[0] and param[1] are initialized with fBG_const and fBG_linear, so in the end the bg is maintained.

Thanks!
Juan

**Pull request closed without merging**
